// One-time seed data for the Protocol CRM pipeline, transcribed from
// "Protocol-Sales-Tracker.xlsx" (the sponsor/venue outreach tracker Vlad
// and the team were running in Google Sheets before this module existed).
// Seeded automatically, once, the first time anyone opens the Protocol CRM
// page — see getOrSeedProtocolLeads() in protocol-crm-server.ts. Editing a
// lead afterward never re-seeds it; this only fires when the table is empty.

export type ProtocolLeadSeed = {
  companyName: string;
  leadType: "SPONSOR" | "VENUE";
  industry: string | null;
  contactName: string | null;
  contactTitle: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  source: string | null;
  assignedRep: string | null;
  priority: "HOT" | "WARM" | "COLD" | null;
  status: "NEW" | "CONTACTED" | "QUALIFYING" | "PROPOSAL_SENT" | "NEGOTIATING" | "FOLLOW_UP_SCHEDULED" | "WON" | "LOST" | "ON_HOLD";
  dateFirstContacted: Date | null;
  lastContactDate: Date | null;
  totalTouches: number;
  lastConversationSummary: string | null;
  nextStep: string | null;
  nextFollowUpDate: Date | null;
  followUpOwner: string | null;
  eventOpportunity: string | null;
  dealValue: number | null;
  notes: string | null;
};

export const PROTOCOL_LEAD_SEED: ProtocolLeadSeed[] = [
  {
    companyName: "Chalet Rive-Sud Events",
    leadType: "VENUE",
    industry: "Event Space",
    contactName: "Marie Tremblay",
    contactTitle: "General Manager",
    phone: "450-555-0134",
    email: "marie@chaletrivesud.ca",
    website: "chaletrivesud.ca",
    source: "Cold Call",
    assignedRep: "Rep 1",
    priority: "HOT",
    status: "NEGOTIATING",
    dateFirstContacted: new Date("2026-07-14T00:00:00.000Z"),
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: "Interested in hosting a brand activation day; wants a formal proposal with insurance details.",
    nextStep: "Send venue rental proposal + certificate of insurance",
    nextFollowUpDate: new Date("2026-08-11T00:00:00.000Z"),
    followUpOwner: "Rep 1",
    eventOpportunity: "Fall Activation Day",
    dealValue: 3500.0,
    notes: "Prefers weekday bookings; ask about parking capacity.",
  },
  {
    companyName: "Lululemon",
    leadType: "SPONSOR",
    industry: "Activewear",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: "Networking",
    assignedRep: "Marwa",
    priority: "COLD",
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Mateina",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: "Marwa",
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "BioSteel",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Flow Water",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "On Running",
    leadType: "SPONSOR",
    industry: "Activewear",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "HOKA",
    leadType: "SPONSOR",
    industry: "Activewear",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "WHOOP",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Therabody",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Hyperice",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "NOBULL",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Liquid Death",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Buddha Brands",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "PRIME Hydration",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Cove Soda",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Blume",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Rise Kombucha",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Arc'teryx",
    leadType: "SPONSOR",
    industry: "Activewear",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "New Balance Canada",
    leadType: "SPONSOR",
    industry: "Activewear",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Normatec",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Garmin",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Mid-Day Squares",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Goodfood",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Organika",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Genuine Health",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Vega",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Evive",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Loop Mission",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Wealthsimple",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Evive",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Oura",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "LMNT",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Olipop",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Poppi",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Chobani",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Siggi's",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "RXBAR",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Barebells",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Runa Energy",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "GT's Living Foods",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Health-Ade Kombucha",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Nespresso Canada",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Gymshark",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Ciele Athletics",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Adidas Canada",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Nike Running",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Salt & Stone",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Aesop",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Shopify",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Air Canada",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Bell",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "TELUS",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Fizz Mobile",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Rogers",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "BMO",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "RBC",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "CIBC",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "TD",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "American Express",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Visa",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Mastercard",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "EQ Bank",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "KOHO",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Neo Financial",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Klean Athlete",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Momentous",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Transparent Labs",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Thorne",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Ritual",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Cymbiotika",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Garden of Life",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "NOW Foods",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "KIND Snacks",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Nature's Path",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "MadeGood",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "SmartSweets",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Unreal Snacks",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "That's it.",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Lärabar",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Clif Bar",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Bobo's",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Hippeas",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Waterloo Sparkling Water",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "San Pellegrino",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Perrier",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Sanzo",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Fever-Tree",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "SimplyProtein",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Remedy Kombucha",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Hiyo",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Kin Euphorics",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Odyssey Elixir",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "GoPro",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "DJI",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Canon Canada",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Canon Canada",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Fujifilm Canada",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Insta360",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Anker",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Beats by Dre",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "JBL",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Logitech",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Dove",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "CeraVe",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "La Roche-Posay",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Vichy",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Biotherm",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Drunk Elephant",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Supergoop!",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "EltaMD",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "The Ordinary",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "MEC",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Patagonia",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Hydro Flask",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Desjardins",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Dropbox",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Mailchimp",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Adobe",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Canva",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Oura",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Vuori",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Polestar",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Audi",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "BMW",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "SEVN",
    leadType: "SPONSOR",
    industry: "Hydration beverage",
    contactName: "Cyril El-Chamy and Sam Auran",
    contactTitle: "Founder and assistant",
    phone: null,
    email: "sam@takesevn.com",
    website: null,
    source: "Inbound / Website",
    assignedRep: "Marwa",
    priority: "WARM",
    status: "QUALIFYING",
    dateFirstContacted: new Date("2026-08-02T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-06T00:00:00.000Z"),
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "IDOLEM (VERDUN)",
    leadType: "VENUE",
    industry: "Gym venue",
    contactName: "ANNIE ALIX PARÉ (Fannie Owner)",
    contactTitle: "Markeking Manager",
    phone: "514-699-8536",
    email: "annie.alix-pare@idolem.com",
    website: "idolem.com",
    source: "Referral",
    assignedRep: "Vlad",
    priority: "HOT",
    status: "NEGOTIATING",
    dateFirstContacted: new Date("2026-07-26T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-07T00:00:00.000Z"),
    totalTouches: 3,
    lastConversationSummary: "Came to see the studio in person and negotiated for the overnight yoga event. Will be meeting up on Monday in person to talk about the details of the event and final price. They wrote an email and want to go for 1000$ as the budget. Good opportunity to do alternations between Yoga and AFTR:HOURS. Price to the person who did all of them or most of them, they have to get stamps for doing all the sessions or most of them.",
    nextStep: "Meeting Monday August 10th",
    nextFollowUpDate: new Date("2026-08-10T00:00:00.000Z"),
    followUpOwner: null,
    eventOpportunity: "Over night Yoga",
    dealValue: 1000.0,
    notes: "Tight budget, they want to put their own coaches",
  },
  {
    companyName: "Gutsy",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: "Pierrich (Owner)",
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: "Marwa",
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Mate Libre",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: "Édouard Dufour-Boiteau",
    contactTitle: "CEO",
    phone: "866-251-0999",
    email: "mate@matelibre.com",
    website: "https://matelibre.com/",
    source: "Cold Email",
    assignedRep: "Sonya",
    priority: null,
    status: "CONTACTED",
    dateFirstContacted: new Date("2026-08-11T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-11T00:00:00.000Z"),
    totalTouches: 0,
    lastConversationSummary: "Email sent in French to contact email on IG (post on Aug.3 asking for ambassadors), so it probably went to a management team. Will follow-up more directly (eg. LinkedIn message)",
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Guru Energy",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: "sponsorships@guruenergy.com",
    website: null,
    source: "Cold Email",
    assignedRep: "Sonya",
    priority: null,
    status: "CONTACTED",
    dateFirstContacted: new Date("2026-08-14T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-14T00:00:00.000Z"),
    totalTouches: 0,
    lastConversationSummary: "Email sent in both languages",
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Healthy Sips",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: "Instagram DM",
    assignedRep: "Sonya",
    priority: null,
    status: "CONTACTED",
    dateFirstContacted: new Date("2026-08-10T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-10T00:00:00.000Z"),
    totalTouches: 0,
    lastConversationSummary: "DM'd to see if they'd distribute. Not in QC yet, but ON right now - Made in Manitoba.",
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Groupe Pro Vert",
    leadType: "VENUE",
    industry: "Event Collab(environmental)",
    contactName: "Nicole Bastien",
    contactTitle: "Managing Director",
    phone: null,
    email: "info@provert.org, replied from nicole@provert.org",
    website: null,
    source: "Cold Email",
    assignedRep: "Sonya",
    priority: null,
    status: "CONTACTED",
    dateFirstContacted: new Date("2026-08-14T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-16T00:00:00.000Z"),
    totalTouches: 2,
    lastConversationSummary: "Email to see if they're interested in a potential collaboration, replied a few days later: on vac, will get back to us (back in 2 weeks)",
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "XACT Nutrition",
    leadType: "SPONSOR",
    industry: "Nutrition brand",
    contactName: "Lawrence Colsell",
    contactTitle: "Co-founder, marketing",
    phone: null,
    email: "info@xactnutrition.com, replied from lawrence@xactnutrition.com",
    website: null,
    source: "Cold Email",
    assignedRep: "Sonya",
    priority: "WARM",
    status: "QUALIFYING",
    dateFirstContacted: new Date("2026-08-14T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-24T00:00:00.000Z"),
    totalTouches: 3,
    lastConversationSummary: "Phone call with Sonya August 25 for 1st intro discussion,",
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Fit Plans",
    leadType: "SPONSOR",
    industry: "Nutrition brand",
    contactName: "? Through Instagram DM",
    contactTitle: null,
    phone: null,
    email: "Sent DM, they replied after asking if they're open to sponsorship/event collab..(pending)",
    website: null,
    source: "Instagram",
    assignedRep: "Sonya",
    priority: null,
    status: "CONTACTED",
    dateFirstContacted: new Date("2026-08-24T00:00:00.000Z"),
    lastContactDate: new Date("2026-08-24T00:00:00.000Z"),
    totalTouches: 2,
    lastConversationSummary: "DM message and reply. Shared about Protocol, they responded with initial interest .. to be cont'd.",
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: null,
  },
  {
    companyName: "Naak Nutrition",
    leadType: "SPONSOR",
    industry: "Nutrition brand",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "Map Hydration",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "Shape (Mocktails)",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "Probites",
    leadType: "SPONSOR",
    industry: "Nutrition brand",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "HulkMeal",
    leadType: "SPONSOR",
    industry: "Nutrition brand",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "Shop Santé*who's contact is this?",
    leadType: "SPONSOR",
    industry: "Nutrition store (local, multiple stores)",
    contactName: "We should re-pitch to these guys",
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "Celsius",
    leadType: "SPONSOR",
    industry: null,
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
  {
    companyName: "Sparkling Ice",
    leadType: "SPONSOR",
    industry: "Beverage",
    contactName: null,
    contactTitle: null,
    phone: null,
    email: null,
    website: null,
    source: null,
    assignedRep: null,
    priority: null,
    status: "NEW",
    dateFirstContacted: null,
    lastContactDate: null,
    totalTouches: 0,
    lastConversationSummary: null,
    nextStep: null,
    nextFollowUpDate: null,
    followUpOwner: null,
    eventOpportunity: null,
    dealValue: null,
    notes: "Contact info not found yet — needs research.",
  },
];
