"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Send, SkipForward, XCircle, Sparkles, ExternalLink, RefreshCw } from "lucide-react";

type Draft = {
  id: string;
  subject: string;
  body: string;
  researchNotes: string | null;
  createdAt: string;
  stepOrder: number;
  stepCount: number;
  sequenceName: string;
  contact: { id: string; number: number; contactName: string; companyName: string | null; email: string | null };
};

// Every draft here was already generated by the background tick (see
// src/lib/sequence-drafts.ts) — this page is purely the human-in-the-loop
// checkpoint: read the researched observation, fix it if it's off, and
// only then does anything actually go out.
export function AutomationConfirmationsShell({ initialDrafts }: { initialDrafts: Draft[] }) {
  const router = useRouter();
  const [drafts, setDrafts] = useState(initialDrafts);
  const [checking, setChecking] = useState(false);
  const [checkResult, setCheckResult] = useState<string | null>(null);

  // router.refresh() re-renders this from the server with new initialDrafts
  // (e.g. after "Check for new drafts now" creates one) — sync local state
  // so a freshly-drafted step actually shows up without a full reload.
  useEffect(() => {
    setDrafts(initialDrafts);
  }, [initialDrafts]);

  function remove(id: string) {
    setDrafts((prev) => prev.filter((d) => d.id !== id));
  }

  // Enrolling a lead (or a step becoming due) doesn't draft anything until
  // the background tick next runs — this fires that same pass on demand,
  // so a newly-due step's draft shows up right away instead of waiting.
  async function checkNow() {
    setChecking(true);
    setCheckResult(null);
    const res = await fetch("/api/automation-confirmations/run-now", { method: "POST" });
    const d = await res.json().catch(() => null);
    setChecking(false);
    if (!res.ok || !d) {
      setCheckResult("Failed to check for new drafts.");
      return;
    }
    setCheckResult(
      d.checked === 0
        ? "No steps are due yet — nothing to draft right now."
        : `Checked ${d.checked} due step${d.checked === 1 ? "" : "s"}, drafted ${d.drafted}.`
    );
    router.refresh();
  }

  const checkButton = (
    <div className="mb-4 flex items-center gap-3">
      <button
        onClick={checkNow}
        disabled={checking}
        className="flex items-center gap-1.5 rounded-full border border-[var(--hq-card-border)] bg-white px-4 py-1.5 text-sm font-medium text-[var(--hq-text)] disabled:opacity-50"
      >
        <RefreshCw className={`h-3.5 w-3.5 ${checking ? "animate-spin" : ""}`} />
        {checking ? "Checking…" : "Check for new drafts now"}
      </button>
      {checkResult && <p className="text-xs text-[var(--hq-text-muted)]">{checkResult}</p>}
    </div>
  );

  if (drafts.length === 0) {
    return (
      <div className="mt-6">
        {checkButton}
        <div className="rounded-xl border border-dashed border-[var(--hq-card-border)] p-8 text-center">
          <p className="text-sm text-[var(--hq-text-muted)]">Nothing waiting on confirmation right now.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="mt-6">
      {checkButton}
      <div className="space-y-4">
        {drafts.map((d) => (
          <DraftCard key={d.id} draft={d} onHandled={() => remove(d.id)} />
        ))}
      </div>
    </div>
  );
}

function DraftCard({ draft, onHandled }: { draft: Draft; onHandled: () => void }) {
  const router = useRouter();
  const [subject, setSubject] = useState(draft.subject);
  const [body, setBody] = useState(draft.body);
  const [busy, setBusy] = useState<"send" | "skip" | "cancel" | null>(null);
  const [error, setError] = useState<string | null>(null);

  const needsResearchReview = !!draft.researchNotes;
  const researchLooksThin =
    draft.researchNotes && /not available|didn't turn up anything|fill in|by hand/i.test(draft.researchNotes);

  async function send() {
    setBusy("send");
    setError(null);
    const res = await fetch(`/api/automation-confirmations/${draft.id}/send`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ subject, body }),
    });
    const d = await res.json().catch(() => ({}));
    setBusy(null);
    if (!res.ok) {
      setError(d.error || "Failed to send.");
      return;
    }
    onHandled();
    router.refresh();
  }

  async function reject(action: "skip" | "cancel") {
    if (action === "cancel" && !confirm(`Cancel the whole "${draft.sequenceName}" sequence for ${draft.contact.contactName}?`)) return;
    setBusy(action);
    setError(null);
    const res = await fetch(`/api/automation-confirmations/${draft.id}/reject`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action }),
    });
    const d = await res.json().catch(() => ({}));
    setBusy(null);
    if (!res.ok) {
      setError(d.error || "Failed.");
      return;
    }
    onHandled();
    router.refresh();
  }

  return (
    <div className="rounded-xl border border-[var(--hq-card-border)] bg-white p-4">
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div>
          <Link
            href={`/dashboard/protocol-crm/${draft.contact.id}`}
            className="flex items-center gap-1 text-sm font-semibold text-[var(--hq-text)] hover:text-[var(--hq-accent)]"
          >
            {draft.contact.companyName || draft.contact.contactName}
            <ExternalLink className="h-3 w-3" />
          </Link>
          <p className="text-xs text-[var(--hq-text-muted)]">
            {draft.contact.contactName}
            {draft.contact.email ? ` · ${draft.contact.email}` : ""} · Lead #{draft.contact.number}
          </p>
        </div>
        <span className="rounded-full bg-[var(--hq-canvas)] px-2.5 py-1 text-xs font-medium text-[var(--hq-text-muted)]">
          {draft.sequenceName} — Email {draft.stepOrder + 1} of {draft.stepCount}
        </span>
      </div>

      {needsResearchReview && (
        <div
          className={`mt-3 flex items-start gap-2 rounded-lg border p-3 text-xs ${
            researchLooksThin
              ? "border-amber-300 bg-amber-50 text-amber-900"
              : "border-[var(--hq-accent)]/30 bg-[var(--hq-accent)]/5 text-[var(--hq-text)]"
          }`}
        >
          <Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <p>{draft.researchNotes}</p>
        </div>
      )}

      <div className="mt-3 space-y-2">
        <input
          className="w-full rounded-md border border-[var(--hq-card-border)] px-3 py-2 text-sm font-medium"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
        />
        <textarea
          rows={10}
          className="w-full rounded-md border border-[var(--hq-card-border)] px-3 py-2 text-sm"
          value={body}
          onChange={(e) => setBody(e.target.value)}
        />
      </div>

      {error && <p className="mt-2 text-sm text-red-600">{error}</p>}

      <div className="mt-3 flex flex-wrap gap-2">
        <button
          onClick={send}
          disabled={busy !== null}
          className="flex items-center gap-1.5 rounded-full bg-[var(--hq-accent)] px-4 py-2 text-sm font-medium text-white disabled:opacity-50"
        >
          <Send className="h-3.5 w-3.5" /> {busy === "send" ? "Sending…" : "Confirm & send"}
        </button>
        <button
          onClick={() => reject("skip")}
          disabled={busy !== null}
          className="flex items-center gap-1.5 rounded-full border border-[var(--hq-card-border)] px-4 py-2 text-sm font-medium text-[var(--hq-text)] disabled:opacity-50"
        >
          <SkipForward className="h-3.5 w-3.5" /> {busy === "skip" ? "Skipping…" : "Skip this one"}
        </button>
        <button
          onClick={() => reject("cancel")}
          disabled={busy !== null}
          className="flex items-center gap-1.5 rounded-full border border-[var(--hq-card-border)] px-4 py-2 text-sm font-medium text-red-600 disabled:opacity-50"
        >
          <XCircle className="h-3.5 w-3.5" /> {busy === "cancel" ? "Canceling…" : "Cancel sequence"}
        </button>
      </div>
    </div>
  );
}
